pub mod analyzer;
pub mod argument;
pub mod assignment;
pub mod definition;
pub mod expression;
pub mod location;
pub mod module;
pub mod operator;
pub mod print;
pub mod reassignment;
pub mod statement;
pub mod typed_print;
mod build_in_functions;