name: Cargo CI
on:
  pull_request:
  push:
    branches:
      - main
env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true
jobs:
  ci:
    name: CI
    runs-on: ubuntu-22.04
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - name: Install Clippy
        run: rustup component add clippy
      - name: Cargo check
        run: cargo check
      - name: Cargo test
        run: cargo test
      - name: Run Clippy
        run: cargo clippy
      - name: Cargo build release
        run: cargo build --release
      - name: Run `awa check` on all benchmarks
        run: |
          cargo run --release --quiet -- check benchmarks/factorial.awa
          cargo run --release --quiet -- check benchmarks/sort.awa
          cargo run --release --quiet -- check benchmarks/prime_numbers.awa
          cargo run --release --quiet -- check benchmarks/tree_traversal.awa
      - name: Run `awa run` factorial
        run: cargo run --release --quiet -- run benchmarks/factorial.awa
      - name: Run `awa run` sort
        run: cargo run --release --quiet -- run benchmarks/sort.awa
      - name: Run `awa run` prime numbers
        run: cargo run --release --quiet -- run benchmarks/prime_numbers.awa
      - name: Run `awa run` tree traversal
        run: cargo run --release --quiet -- run benchmarks/tree_traversal.awa
